//! Golden-file tests for the `.vmf` container format (`CLAUDE.md` §5: every
//! file-format importer/exporter gets golden-file tests in
//! `tests/fixtures/`). These pin acceptance criterion 7's three refusal
//! cases against committed byte-for-byte fixtures, not just bytes built
//! fresh inside a unit test — so a future change to `pack`/`unpack` that
//! can no longer read a file *this build already wrote* fails here.
//!
//! Fixtures are regenerated by `vecmanf_document_core::container::tests::
//! generate_golden_fixtures` (an `#[ignore]`d test) when the container
//! format changes deliberately.

// This whole file is test code (an integration test crate under `tests/`),
// so `CLAUDE.md` §5's unwrap/expect restriction does not apply here.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use vecmanf_document_core::{OpenError, unpack};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|err| panic!("reading fixture {}: {err}", path.display()))
}

#[test]
fn valid_vmf_opens_without_error() {
    let bytes = fixture("valid.vmf");
    let document = unpack(&bytes).expect("a golden valid .vmf must open");
    let size = document.size();
    assert!((size.width.as_mm() - 210.0).abs() < f64::EPSILON);
    assert!((size.height.as_mm() - 297.0).abs() < f64::EPSILON);
}

#[test]
fn not_a_vmf_is_refused_as_such() {
    let bytes = fixture("not_a_vmf.txt");
    assert!(matches!(unpack(&bytes), Err(OpenError::NotAVmf)));
}

#[test]
fn truncated_vmf_is_refused_as_damaged() {
    let bytes = fixture("truncated.vmf");
    assert!(matches!(unpack(&bytes), Err(OpenError::Damaged)));
}

#[test]
fn future_format_version_vmf_is_refused_as_too_new() {
    let bytes = fixture("future_format_version.vmf");
    assert!(matches!(
        unpack(&bytes),
        Err(OpenError::FormatTooNew { .. })
    ));
}
