//! Golden-file tests for the `.vmf` container format (`CLAUDE.md` §5: every
//! file-format importer/exporter gets golden-file tests in
//! `tests/fixtures/`). These pin acceptance criterion 7's three refusal
//! cases against committed byte-for-byte fixtures, not just bytes built
//! fresh inside a unit test — so a future change to `pack`/`unpack` that
//! can no longer read a file *this build already wrote* fails here.
//!
//! Fixtures are regenerated by `vecmanf_document_core::container::tests::
//! generate_golden_fixtures` (an `#[ignore]`d test) when the container
//! format changes deliberately.

// This whole file is test code (an integration test crate under `tests/`),
// so `CLAUDE.md` §5's unwrap/expect restriction does not apply here.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use vecmanf_document_core::{AnchorKind, OpenError, unpack};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|err| panic!("reading fixture {}: {err}", path.display()))
}

#[test]
fn valid_vmf_opens_without_error() {
    let bytes = fixture("valid.vmf");
    let document = unpack(2, &bytes).expect("a golden valid .vmf must open");
    let size = document.size();
    assert!((size.width.as_mm() - 210.0).abs() < f64::EPSILON);
    assert!((size.height.as_mm() - 297.0).abs() < f64::EPSILON);
}

#[test]
fn not_a_vmf_is_refused_as_such() {
    let bytes = fixture("not_a_vmf.txt");
    assert!(matches!(unpack(2, &bytes), Err(OpenError::NotAVmf)));
}

#[test]
fn truncated_vmf_is_refused_as_damaged() {
    let bytes = fixture("truncated.vmf");
    assert!(matches!(unpack(2, &bytes), Err(OpenError::Damaged)));
}

#[test]
fn future_format_version_vmf_is_refused_as_too_new() {
    let bytes = fixture("future_format_version.vmf");
    assert!(matches!(
        unpack(2, &bytes),
        Err(OpenError::FormatTooNew { .. })
    ));
}

/// `path-node-editing` (`specs/0002-path-node-editing/plan.md`, task 31): a
/// `format_version = 2` document with two paths — one open with only
/// corner anchors, one closed with a mix of corner and smooth anchors and
/// real (non-zero) handles — round-trips through the container exactly.
#[test]
fn paths_v2_vmf_round_trips_both_anchor_kinds_open_and_closed() {
    let bytes = fixture("paths_v2.vmf");
    let document = unpack(2, &bytes).expect("a golden paths .vmf must open");

    let ids = document.path_ids();
    assert_eq!(ids.len(), 2, "exactly two paths");

    let open = document.path(ids[0]).expect("first path exists");
    assert!(!open.closed);
    assert_eq!(open.anchors.len(), 2);
    assert!(open.anchors.iter().all(|a| a.kind == AnchorKind::Corner));

    let closed = document.path(ids[1]).expect("second path exists");
    assert!(closed.closed);
    assert_eq!(closed.anchors.len(), 3);
    assert_eq!(closed.anchors[0].kind, AnchorKind::Corner);
    assert_eq!(closed.anchors[1].kind, AnchorKind::Smooth);
    assert_ne!(
        closed.anchors[1].handle_out,
        vecmanf_document_core::Vec2::ZERO
    );
}

/// `path-node-editing`'s written migration policy
/// (`specs/0002-path-node-editing/adrs.md`, "`format_version` goes to 2"): a
/// genuine `format_version = 1` container — written before paths existed
/// at all — still opens, with an empty path list rather than an error or a
/// partial read.
#[test]
fn format_version_1_vmf_opens_with_no_paths() {
    let bytes = fixture("format_version_1.vmf");
    let document = unpack(2, &bytes).expect("a golden format_version=1 .vmf must still open");
    assert_eq!(document.path_ids(), Vec::new());
}

/// Architect review (`specs/0002-path-node-editing/adrs.md`'s PR review note):
/// a container whose `paths` tree does not match the schema
/// `vecmanf_document_core::paths` writes is refused with
/// `OpenError::Damaged`, the same "not a crash" guarantee
/// `project-file-foundation`'s acceptance criterion 7 already gives
/// slice 1's own three refusal cases.
#[test]
fn malformed_paths_vmf_is_refused_as_damaged_not_a_panic() {
    let bytes = fixture("malformed_paths.vmf");
    assert!(matches!(unpack(2, &bytes), Err(OpenError::Damaged)));
}
