// Loads the vecmanf-editor-wasm facade (ADR 0001 §3) and mints the fresh
// Loro peer id each open editing session needs
// (specs/project-file-foundation/adrs.md, "a fresh Loro peer id per open
// session" — vecmanf-app/src/state.rs::mint_peer_id() mints the native
// side's copy the same way; this is the wasm facade's own session, not
// the same Document, so it mints its own).
//
// frontend/src/wasm-bindings/ is generated by scripts/build-wasm.sh
// (wired as npm's predev/prebuild) and not committed — see
// frontend/.gitignore. This import only resolves once that has run.
import init, {
  WasmSession,
  init_panic_hook,
} from "@/wasm-bindings/vecmanf_editor_wasm.js";

let ready: Promise<void> | null = null;

/** Initializes the wasm module exactly once, however many editor
 * sessions open over the app's lifetime. */
function loadOnce(): Promise<void> {
  ready ??= init().then(() => {
    init_panic_hook();
  });
  return ready;
}

/** A fresh Loro peer id for one open editing session — the browser's own
 * CSPRNG, since `vecmanf-document-core`/`vecmanf-ui-core` cannot draw one
 * themselves (`CLAUDE.md` §6: a `*-core` crate reaches no entropy
 * source). The top bit is cleared so every consumer along the way (a
 * Rust `u64`, a JS `bigint`, `wasm-bindgen`'s own marshalling) agrees on
 * the value without relying on unsigned 64-bit wraparound anywhere. */
function mintPeerId(): bigint {
  const bytes = new Uint8Array(8);
  crypto.getRandomValues(bytes);
  let value = 0n;
  for (const byte of bytes) {
    value = (value << 8n) | BigInt(byte);
  }
  return value & 0x7f_ff_ff_ff_ff_ff_ff_ffn;
}

/** Creates a brand-new, empty editing session, ready to attach to a
 * canvas. */
export async function createSession(): Promise<WasmSession> {
  await loadOnce();
  return new WasmSession(mintPeerId());
}

/** Reopens a previously saved `.vmf` container's bytes as a fresh editing
 * session (File → Open / the OS file association), bound to a freshly
 * minted peer id the same way `createSession` is.
 *
 * `specs/path-node-editing/adrs.md`'s PR review: "Open reads bytes and
 * calls `WasmSession::open`" — the host (`vecmanf-app`) only ever reads
 * these bytes off disk; this is the one place they are actually parsed.
 *
 * @throws the exact user-facing sentence
 * `specs/project-file-foundation/specification.md`'s "Error handling —
 * invalid/corrupt file" names, if `bytes` is not a `.vmf` this build can
 * open (`vecmanf-editor-wasm`'s `map_open_error`). */
export async function openSession(bytes: Uint8Array): Promise<WasmSession> {
  await loadOnce();
  return WasmSession.open(mintPeerId(), bytes);
}

export type { WasmSession, NodeToolbarState } from "@/wasm-bindings/vecmanf_editor_wasm.js";
